name: backend_dart
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  path: ^1.8.0
  shelf: ^1.2.0
  shelf_router: ^1.1.3
  dart_jsonwebtoken: ^2.4.1
  mysql1: ^0.20.0
  password_dart: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
